# Generated by Django 4.1.7 on 2024-03-11 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0002_alter_product_table_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_table',
            name='product_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product_table',
            name='slug',
            field=models.SlugField(max_length=100),
        ),
    ]
