# Generated by Django 4.1.7 on 2024-03-23 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0003_alter_product_table_product_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variation_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variation_category', models.CharField(choices=[('color', 'color'), ('size', 'size')], max_length=100)),
                ('variation_value', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('pt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_app.product_table')),
            ],
        ),
    ]
