# Generated by Django 4.1.7 on 2024-03-20 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email_table',
            name='msg',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
