# Generated by Django 4.1.7 on 2024-03-20 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails_app', '0002_email_table_msg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email_table',
            name='msg',
        ),
    ]
